/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ControlAdminDatos.PersonaDao;
import Controlador.CondenaDao;
import Controlador.DelitoDao;
import Controlador.JuzgadoDao;
import Controlador.ProcesoDao;
import Controlador.Utilidades.UtilAgreGesAnt;
import Modelo.Condena;
import Modelo.Delito;
import Modelo.Juzgado;
import Modelo.Persona;
import Modelo.Proceso;
import Vista.Utiles.UtilesFecha;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import necesario.RSFileChooser;

/**
 *
 * @author hp
 */
public class AgregarAntecedentes extends javax.swing.JPanel {
    
    boolean boolPanelMenu = false;
    boolean boolPanelAntecedentes = false;
    boolean boolPanelPersonas = false;
    boolean boolPanelSettings = false;
    File fichero = null;
    String rutaArchivo;
    ArrayList<Delito> listaDelito;
    DelitoDao dd = new DelitoDao();
    ArrayList<Juzgado> listaJuzgado;
    JuzgadoDao jd = new JuzgadoDao();
    ArrayList<Persona> listaPersonas;
    PersonaDao pd = new PersonaDao();
    ArrayList<Proceso> listaProcesos;
    ProcesoDao prcd = new ProcesoDao();
    CondenaDao cd = new CondenaDao();
    Persona auxPer = null;
    String estadoProceso;
    String estadoVictimario;
    UtilesFecha fecha = new UtilesFecha();

    /**
     * Creates new form AgregarAntecedentes
     */
    public AgregarAntecedentes() {
        initComponents();
        IconoBorrarArchivo.setVisible(false);
        lbIconoArchivo.setVisible(false);
        lbNombreArchivo.setVisible(false);
        rbEnProceso.setEnabled(false);
        rbEnProceso.setSelected(true);
        rbPresuntoCulpable.setSelected(true);
        rbPresuntoCulpable.setEnabled(false);
        this.estadoProceso = "En proceso";
        this.estadoVictimario = "Presunto Culpable";
        listaDelito = dd.findDelitoEntities(false);
        listaJuzgado = jd.findJuzgadoEntities(false);
        listaPersonas = pd.findPersonaEntities();
        listaProcesos = prcd.findProcesoEntities(true);
        cargarCombos();
    }

    /**
     * Limpia todos los campos
     */
    public void limpiarCampos() {
        auxPer = null;
        txtCedula.setText("");
        txtNombreApellido.setText("");
        cbDelito.setSelectedIndex(0);
        txArt.setText("");
        jTextArea1.setText("");
        cbJuzgados.setSelectedIndex(0);
        dcFechaInicioAudiencia.setDate(null);
        dcFechaFinalizacionAudiencia.setDate(null);
        txtIntancia.setText("");
        txtNrAudiencia.setText("");
        txtSentencia.setText("");
        foto.setText("");
        borrarArchivo();
    }

    /**
     * Borra el archivo temporal que se muestra al usuario
     */
    public void borrarArchivo() {
        IconoBorrarArchivo.setVisible(false);
        lbIconoArchivo.setVisible(false);
        lbNombreArchivo.setVisible(false);
        lbNombreArchivo.setText("");
        fichero = null;
    }

    /**
     * Carga los comboBox con los datos correspondientes
     */
    public void cargarCombos() {
        listaDelito = dd.findDelitoEntities(false);
        UtilAgreGesAnt.cargarCombo(cbDelito, listaDelito, "nombre");
        listaJuzgado = jd.findJuzgadoEntities(false);
        UtilAgreGesAnt.cargarCombo(cbJuzgados, listaJuzgado, "nombre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        PanelComponentes = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombreApellido = new javax.swing.JTextField();
        lbLinea = new javax.swing.JLabel();
        lbNombreApellido = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbArt = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbDelito = new javax.swing.JLabel();
        txArt = new javax.swing.JTextField();
        cbDelito = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbJuzgado = new javax.swing.JLabel();
        cbJuzgados = new javax.swing.JComboBox<>();
        lbDescripcionDelito1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dcFechaInicioAudiencia = new com.toedter.calendar.JDateChooser();
        lbFechaInicioAudiencia = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbFechaInicioAudiencia1 = new javax.swing.JLabel();
        dcFechaFinalizacionAudiencia = new com.toedter.calendar.JDateChooser();
        lbIntancia = new javax.swing.JLabel();
        txtIntancia = new javax.swing.JTextField();
        lbNrAudiencia = new javax.swing.JLabel();
        txtNrAudiencia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rbEnProceso = new javax.swing.JRadioButton();
        rbFinalizado = new javax.swing.JRadioButton();
        lbEstadoProceso = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbSentencia = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSentencia = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lbNombreArchivo = new javax.swing.JLabel();
        lbIconoArchivo = new javax.swing.JLabel();
        IconoBorrarArchivo = new javax.swing.JLabel();
        botonSubir = new javax.swing.JPanel();
        lbSubirArchivo = new javax.swing.JLabel();
        lbIconoSubir = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JPanel();
        IconoBuscar = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JPanel();
        lbIconoGuardar = new javax.swing.JLabel();
        lbGuardar = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbEstadoProceso1 = new javax.swing.JLabel();
        rbCulpable = new javax.swing.JRadioButton();
        rbPresuntoCulpable = new javax.swing.JRadioButton();
        rbInocente = new javax.swing.JRadioButton();
        foto = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 610));
        setPreferredSize(new java.awt.Dimension(1000, 610));
        setLayout(null);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(1072, 600));

        PanelComponentes.setBackground(new java.awt.Color(255, 255, 255));
        PanelComponentes.setMinimumSize(new java.awt.Dimension(1000, 1100));
        PanelComponentes.setPreferredSize(new java.awt.Dimension(1000, 1100));
        PanelComponentes.setVerifyInputWhenFocusTarget(false);
        PanelComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelComponentesMouseExited(evt);
            }
        });
        PanelComponentes.setLayout(null);

        LabelTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        LabelTitulo.setText("AGREGAR ANTECEDENTES");
        LabelTitulo.setToolTipText("");
        PanelComponentes.add(LabelTitulo);
        LabelTitulo.setBounds(233, 11, 274, 32);

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        PanelComponentes.add(txtCedula);
        txtCedula.setBounds(50, 90, 219, 30);

        txtNombreApellido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreApellido.setEnabled(false);
        txtNombreApellido.setOpaque(false);
        txtNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApellidoActionPerformed(evt);
            }
        });
        PanelComponentes.add(txtNombreApellido);
        txtNombreApellido.setBounds(360, 90, 319, 30);

        lbLinea.setText("_________________________________________________________________________________________________________________________________________________________________");
        lbLinea.setMaximumSize(new java.awt.Dimension(600, 14));
        lbLinea.setPreferredSize(new java.awt.Dimension(600, 14));
        PanelComponentes.add(lbLinea);
        lbLinea.setBounds(0, 191, 971, 20);

        lbNombreApellido.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNombreApellido.setText("Nombre y Apellido");
        lbNombreApellido.setToolTipText("");
        PanelComponentes.add(lbNombreApellido);
        lbNombreApellido.setBounds(360, 50, 114, 20);

        lbCedula.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbCedula.setText("Cédula");
        lbCedula.setToolTipText("");
        PanelComponentes.add(lbCedula);
        lbCedula.setBounds(50, 50, 42, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        PanelComponentes.add(jLabel11);
        jLabel11.setBounds(40, 50, 10, 17);

        lbArt.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbArt.setText("Art:");
        lbArt.setToolTipText("");
        PanelComponentes.add(lbArt);
        lbArt.setBounds(70, 280, 21, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        PanelComponentes.add(jLabel16);
        jLabel16.setBounds(60, 220, 10, 17);

        lbDelito.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDelito.setText("Delito:");
        lbDelito.setToolTipText("");
        PanelComponentes.add(lbDelito);
        lbDelito.setBounds(70, 230, 38, 20);

        txArt.setText("N");
        txArt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txArt.setEnabled(false);
        txArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txArtActionPerformed(evt);
            }
        });
        PanelComponentes.add(txArt);
        txArt.setBounds(160, 280, 110, 30);

        cbDelito.setBackground(new java.awt.Color(240, 240, 240));
        cbDelito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDelito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDelitoItemStateChanged(evt);
            }
        });
        PanelComponentes.add(cbDelito);
        cbDelito.setBounds(160, 220, 530, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        PanelComponentes.add(jScrollPane2);
        jScrollPane2.setBounds(160, 330, 361, 76);

        lbJuzgado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbJuzgado.setText("Juzgado:");
        lbJuzgado.setToolTipText("");
        PanelComponentes.add(lbJuzgado);
        lbJuzgado.setBounds(76, 441, 53, 20);

        cbJuzgados.setBackground(new java.awt.Color(240, 240, 240));
        cbJuzgados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbJuzgados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJuzgadosItemStateChanged(evt);
            }
        });
        PanelComponentes.add(cbJuzgados);
        cbJuzgados.setBounds(160, 440, 360, 30);

        lbDescripcionDelito1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDescripcionDelito1.setText("Descripción:");
        lbDescripcionDelito1.setToolTipText("");
        PanelComponentes.add(lbDescripcionDelito1);
        lbDescripcionDelito1.setBounds(70, 330, 73, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");
        PanelComponentes.add(jLabel19);
        jLabel19.setBounds(60, 443, 10, 17);

        dcFechaInicioAudiencia.setDateFormatString("dd/MM/yyyy");
        dcFechaInicioAudiencia.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));
        PanelComponentes.add(dcFechaInicioAudiencia);
        dcFechaInicioAudiencia.setBounds(320, 476, 130, 30);

        lbFechaInicioAudiencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbFechaInicioAudiencia.setText("Fecha de Inicio de la Audiencia:");
        lbFechaInicioAudiencia.setToolTipText("");
        PanelComponentes.add(lbFechaInicioAudiencia);
        lbFechaInicioAudiencia.setBounds(76, 486, 188, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("*");
        PanelComponentes.add(jLabel20);
        jLabel20.setBounds(60, 488, 10, 17);

        lbFechaInicioAudiencia1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbFechaInicioAudiencia1.setText("Fecha de Finalización de la Audiencia:");
        lbFechaInicioAudiencia1.setToolTipText("");
        PanelComponentes.add(lbFechaInicioAudiencia1);
        lbFechaInicioAudiencia1.setBounds(76, 534, 226, 20);

        dcFechaFinalizacionAudiencia.setDateFormatString("dd/MM/yyyy");
        dcFechaFinalizacionAudiencia.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));
        PanelComponentes.add(dcFechaFinalizacionAudiencia);
        dcFechaFinalizacionAudiencia.setBounds(320, 524, 130, 30);

        lbIntancia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbIntancia.setText("Intancia:");
        lbIntancia.setToolTipText("");
        PanelComponentes.add(lbIntancia);
        lbIntancia.setBounds(76, 575, 49, 20);

        txtIntancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntanciaActionPerformed(evt);
            }
        });
        txtIntancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntanciaKeyTyped(evt);
            }
        });
        PanelComponentes.add(txtIntancia);
        txtIntancia.setBounds(143, 572, 66, 30);

        lbNrAudiencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNrAudiencia.setText("Nr Audiencia:");
        lbNrAudiencia.setToolTipText("");
        PanelComponentes.add(lbNrAudiencia);
        lbNrAudiencia.setBounds(320, 575, 81, 20);

        txtNrAudiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrAudienciaActionPerformed(evt);
            }
        });
        txtNrAudiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNrAudienciaKeyTyped(evt);
            }
        });
        PanelComponentes.add(txtNrAudiencia);
        txtNrAudiencia.setBounds(419, 572, 66, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("*");
        PanelComponentes.add(jLabel21);
        jLabel21.setBounds(60, 577, 10, 17);

        rbEnProceso.setBackground(new java.awt.Color(255, 255, 255));
        rbEnProceso.setSelected(true);
        rbEnProceso.setText("En Proceso");
        rbEnProceso.setFocusPainted(false);
        rbEnProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnProcesoActionPerformed(evt);
            }
        });
        PanelComponentes.add(rbEnProceso);
        rbEnProceso.setBounds(220, 680, 78, 22);

        rbFinalizado.setBackground(new java.awt.Color(255, 255, 255));
        rbFinalizado.setText("Finalizado");
        rbFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFinalizadoActionPerformed(evt);
            }
        });
        PanelComponentes.add(rbFinalizado);
        rbFinalizado.setBounds(320, 680, 73, 23);

        lbEstadoProceso.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbEstadoProceso.setText("Estado del Victimario:");
        lbEstadoProceso.setToolTipText("");
        PanelComponentes.add(lbEstadoProceso);
        lbEstadoProceso.setBounds(70, 640, 130, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("*");
        PanelComponentes.add(jLabel22);
        jLabel22.setBounds(50, 640, 10, 17);

        lbSentencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbSentencia.setText("Sentencia:");
        lbSentencia.setToolTipText("");
        PanelComponentes.add(lbSentencia);
        lbSentencia.setBounds(76, 710, 60, 20);

        txtSentencia.setColumns(20);
        txtSentencia.setRows(5);
        jScrollPane3.setViewportView(txtSentencia);

        PanelComponentes.add(jScrollPane3);
        jScrollPane3.setBounds(76, 741, 335, 76);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombreArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 317, 21));

        lbIconoArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/PDF file icon_page-0001.png"))); // NOI18N
        lbIconoArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconoArchivoMouseClicked(evt);
            }
        });
        jPanel3.add(lbIconoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        IconoBorrarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCerrar.png"))); // NOI18N
        IconoBorrarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoBorrarArchivoMouseClicked(evt);
            }
        });
        jPanel3.add(IconoBorrarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, -1));

        PanelComponentes.add(jPanel3);
        jPanel3.setBounds(224, 840, 331, 131);

        botonSubir.setBackground(new java.awt.Color(18, 44, 82));
        botonSubir.setPreferredSize(new java.awt.Dimension(140, 46));
        botonSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSubirMouseClicked(evt);
            }
        });

        lbSubirArchivo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbSubirArchivo.setForeground(new java.awt.Color(204, 206, 223));
        lbSubirArchivo.setText("Subir Archivo");

        lbIconoSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoSubir.png"))); // NOI18N

        javax.swing.GroupLayout botonSubirLayout = new javax.swing.GroupLayout(botonSubir);
        botonSubir.setLayout(botonSubirLayout);
        botonSubirLayout.setHorizontalGroup(
            botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSubirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSubirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lbIconoSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        botonSubirLayout.setVerticalGroup(
            botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSubirLayout.createSequentialGroup()
                .addGroup(botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSubirArchivo)
                    .addComponent(lbIconoSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelComponentes.add(botonSubir);
        botonSubir.setBounds(309, 989, 147, 22);

        botonBuscar.setBackground(new java.awt.Color(18, 44, 82));
        botonBuscar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        IconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoBuscar1.png"))); // NOI18N

        lbBuscar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(204, 206, 223));
        lbBuscar.setText("Buscar");

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(IconoBuscar)
                .addContainerGap())
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoBuscar)
                    .addComponent(lbBuscar))
                .addGap(0, 0, 0))
        );

        PanelComponentes.add(botonBuscar);
        botonBuscar.setBounds(327, 163, 105, 22);

        botonGuardar.setBackground(new java.awt.Color(18, 44, 82));
        botonGuardar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        lbIconoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoGuardar.png"))); // NOI18N

        lbGuardar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbGuardar.setForeground(new java.awt.Color(204, 206, 223));
        lbGuardar.setText("Guardar");

        javax.swing.GroupLayout botonGuardarLayout = new javax.swing.GroupLayout(botonGuardar);
        botonGuardar.setLayout(botonGuardarLayout);
        botonGuardarLayout.setHorizontalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lbIconoGuardar)
                .addContainerGap())
        );
        botonGuardarLayout.setVerticalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconoGuardar)
                    .addComponent(lbGuardar))
                .addGap(0, 0, 0))
        );

        PanelComponentes.add(botonGuardar);
        botonGuardar.setBounds(328, 1057, 114, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("*");
        PanelComponentes.add(jLabel23);
        jLabel23.setBounds(200, 840, 10, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("*");
        PanelComponentes.add(jLabel24);
        jLabel24.setBounds(50, 680, 10, 17);

        lbEstadoProceso1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbEstadoProceso1.setText("Estado del Proceso:");
        lbEstadoProceso1.setToolTipText("");
        PanelComponentes.add(lbEstadoProceso1);
        lbEstadoProceso1.setBounds(70, 680, 117, 20);

        rbCulpable.setBackground(new java.awt.Color(255, 255, 255));
        rbCulpable.setText("Culpable");
        rbCulpable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCulpableActionPerformed(evt);
            }
        });
        PanelComponentes.add(rbCulpable);
        rbCulpable.setBounds(220, 640, 67, 23);

        rbPresuntoCulpable.setBackground(new java.awt.Color(255, 255, 255));
        rbPresuntoCulpable.setText("Presunto Culpable");
        rbPresuntoCulpable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPresuntoCulpableActionPerformed(evt);
            }
        });
        PanelComponentes.add(rbPresuntoCulpable);
        rbPresuntoCulpable.setBounds(320, 640, 120, 23);

        rbInocente.setBackground(new java.awt.Color(255, 255, 255));
        rbInocente.setText("Inocente");
        rbInocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInocenteActionPerformed(evt);
            }
        });
        PanelComponentes.add(rbInocente);
        rbInocente.setBounds(470, 640, 70, 23);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/UsuarioImg.png"))); // NOI18N
        PanelComponentes.add(foto);
        foto.setBounds(730, 30, 140, 140);

        jScrollPane4.setViewportView(PanelComponentes);

        add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 1000, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelComponentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelComponentesMouseExited
        txtNombreApellido.setFocusable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PanelComponentesMouseExited
    /**
     * Seleciona el estado Inocente del Victimario
     *
     * @param evt
     */
    private void rbInocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInocenteActionPerformed
        if (rbInocente.isSelected()) {
            rbInocente.setEnabled(false);
            rbCulpable.setEnabled(true);
            rbCulpable.setSelected(false);
            rbPresuntoCulpable.setEnabled(true);
            rbPresuntoCulpable.setSelected(false);
            this.estadoVictimario = "Inocente";
        }
    }//GEN-LAST:event_rbInocenteActionPerformed
    /**
     * Seleciona el estado Presunto Culpable del Victimario
     *
     * @param evt
     */
    private void rbPresuntoCulpableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPresuntoCulpableActionPerformed
        if (rbPresuntoCulpable.isSelected()) {
            rbPresuntoCulpable.setEnabled(false);
            rbCulpable.setEnabled(true);
            rbCulpable.setSelected(false);
            rbInocente.setEnabled(true);
            rbInocente.setSelected(false);
            this.estadoVictimario = "Presunto Culpable";
        }
    }//GEN-LAST:event_rbPresuntoCulpableActionPerformed
    /**
     * Seleciona el estado Culpable del Victimario
     *
     * @param evt
     */
    private void rbCulpableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCulpableActionPerformed
        if (rbCulpable.isSelected()) {
            rbCulpable.setEnabled(false);
            rbPresuntoCulpable.setEnabled(true);
            rbPresuntoCulpable.setSelected(false);
            rbInocente.setEnabled(true);
            rbInocente.setSelected(false);
            this.estadoVictimario = "Culpable";
        }
    }//GEN-LAST:event_rbCulpableActionPerformed
    /**
     * Guarda los datos correspondientes del antecedente o proceso
     *
     * @param evt
     */
    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        if (auxPer != null && txtCedula.getText().length() > 0 && txtNombreApellido.getText().length() > 0
                && cbDelito.getSelectedIndex() > 0 && cbJuzgados.getSelectedIndex() > 0
                && dcFechaInicioAudiencia.getDate() != null && txtIntancia.getText().length() > 0
                && fichero != null) {
            try {
                byte[] pdf = new byte[(int) fichero.length()];
                InputStream input = new FileInputStream(fichero);
                input.read(pdf);
                Delito auxD = listaDelito.get(cbDelito.getSelectedIndex() - 1);
                Juzgado auxJ = listaJuzgado.get(cbJuzgados.getSelectedIndex() - 1);
                Condena auxC = new Condena(Long.valueOf(listaProcesos.size() + 1), txtSentencia.getText(),
                        (!txtSentencia.getText().equalsIgnoreCase("") ? "Dictada" : "Sin Dictar"));
                Proceso auxP = new Proceso(Long.valueOf(listaProcesos.size() + 1), Integer.parseInt(txtIntancia.getText()),
                        fecha.getFecha(dcFechaInicioAudiencia), fecha.getFecha(dcFechaFinalizacionAudiencia),
                        (!txtNrAudiencia.getText().equalsIgnoreCase("")) ? Integer.parseInt(txtNrAudiencia.getText()) : 0,
                        pdf, fichero.getName(), estadoVictimario, (dcFechaFinalizacionAudiencia != null) ? "Finalizado" : estadoProceso,
                        "Habilitado", auxD.getIdDelito(), auxPer.getIdPersona(), auxC.getIdCondena(), auxJ.getIdJuzgado());
                
                if (!UtilAgreGesAnt.datoRepetido(listaProcesos, auxP)) {
                    cd.create(auxC);
                    prcd.create(auxP);
                    if (cd.isSeGuardo() && prcd.isSeGuardo()) {
                        JOptionPane.showMessageDialog(null, "Se ha guardado con exito");
                        listaProcesos = prcd.findProcesoEntities(true);
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Este proceso ya se encuentra registrado");
                }
            } catch (IOException ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
        }
    }//GEN-LAST:event_botonGuardarMouseClicked
    /**
     * Busca los datos de la persona ingresada
     *
     * @param evt
     */
    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        auxPer = (Persona) UtilAgreGesAnt.obtenerEntidad(txtCedula.getText(), listaPersonas, "cedula");
        if (auxPer != null) {
            txtNombreApellido.setText(auxPer.getNombre() + " " + auxPer.getApellido());
            ImageIcon icon = new ImageIcon(auxPer.getFile().getAbsolutePath());
            Image imgEscalada = icon.getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH);
            Icon imgIcon = new ImageIcon(imgEscalada);
            foto.setIcon(imgIcon);
        } else {
            JOptionPane.showMessageDialog(null, "No existe registro de esa persona");
        }
    }//GEN-LAST:event_botonBuscarMouseClicked
    /**
     * Permite subir un archivo
     *
     * @param evt
     */
    private void botonSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSubirMouseClicked
        necesario.RSFileChooser fc = new necesario.RSFileChooser();//Creamos el objeto JFileChooser
        int seleccion = fc.showOpenDialog(this);//Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario selecciona aceptar
            IconoBorrarArchivo.setVisible(true);
            lbIconoArchivo.setVisible(true);
            fichero = fc.getSelectedFile();//Seleccionamos el fichero
            lbNombreArchivo.setVisible(true);
            lbNombreArchivo.setText(fichero.getName());//Escribimos el nombre del archivo
        }
    }//GEN-LAST:event_botonSubirMouseClicked
    /**
     * Permite borrar el archivo subido
     *
     * @param evt
     */
    private void IconoBorrarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoBorrarArchivoMouseClicked
        borrarArchivo();
    }//GEN-LAST:event_IconoBorrarArchivoMouseClicked
    /**
     * Permite descargar el archivo
     *
     * @param evt
     */
    private void lbIconoArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconoArchivoMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                byte[] pdf = new byte[(int) fichero.length()];
                InputStream input = new FileInputStream(fichero);
                input.read(pdf);
                necesario.RSFileChooser guardar = new RSFileChooser();
                guardar.showSaveDialog(null);
                guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                File archivo = guardar.getSelectedFile();
                UtilAgreGesAnt.descargarArchivo(pdf, archivo);
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_lbIconoArchivoMouseClicked
    /**
     * Seleciona el estado Finalizado del Proceso o Jucio
     *
     * @param evt
     */
    private void rbFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFinalizadoActionPerformed
        if (rbFinalizado.isSelected()) {
            rbFinalizado.setEnabled(false);
            rbEnProceso.setEnabled(true);
            rbEnProceso.setSelected(false);
            this.estadoProceso = "Finalizado";
        }
    }//GEN-LAST:event_rbFinalizadoActionPerformed
    /**
     * Seleciona el estado En proceso del Proceso o Jucio
     *
     * @param evt
     */
    private void rbEnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnProcesoActionPerformed
        if (rbEnProceso.isSelected()) {
            rbEnProceso.setEnabled(false);
            rbFinalizado.setEnabled(true);
            rbFinalizado.setSelected(false);
            this.estadoProceso = "En proceso";
        }
    }//GEN-LAST:event_rbEnProcesoActionPerformed

    private void txtNrAudienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrAudienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrAudienciaActionPerformed

    private void txtIntanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntanciaActionPerformed

    private void cbJuzgadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJuzgadosItemStateChanged

    }//GEN-LAST:event_cbJuzgadosItemStateChanged
    /**
     * Carga los datos del delito según la posición
     *
     * @param evt
     */
    private void cbDelitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDelitoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbDelito.getSelectedIndex() == 0) {
                jTextArea1.setText("");
                txArt.setText("");
            } else {
                Delito aux = listaDelito.get(cbDelito.getSelectedIndex() - 1);
                jTextArea1.setText(aux.getDescripcion());
                txArt.setText(aux.getArticulo());
            }
        }
    }//GEN-LAST:event_cbDelitoItemStateChanged

    private void txArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txArtActionPerformed

    private void txtNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApellidoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed
    /**
     * Solo permite numeros en la cedula
     *
     * @param evt
     */
    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped
    /**
     * Solo permite numeros en la instancia
     *
     * @param evt
     */
    private void txtIntanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntanciaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }    }//GEN-LAST:event_txtIntanciaKeyTyped
    /**
     * Solo permite numeros en el número de audiencias
     *
     * @param evt
     */
    private void txtNrAudienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNrAudienciaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }    }//GEN-LAST:event_txtNrAudienciaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoBorrarArchivo;
    private javax.swing.JLabel IconoBuscar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelComponentes;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JPanel botonGuardar;
    private javax.swing.JPanel botonSubir;
    private javax.swing.JComboBox<String> cbDelito;
    private javax.swing.JComboBox<String> cbJuzgados;
    private com.toedter.calendar.JDateChooser dcFechaFinalizacionAudiencia;
    private com.toedter.calendar.JDateChooser dcFechaInicioAudiencia;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbArt;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbDelito;
    private javax.swing.JLabel lbDescripcionDelito1;
    private javax.swing.JLabel lbEstadoProceso;
    private javax.swing.JLabel lbEstadoProceso1;
    private javax.swing.JLabel lbFechaInicioAudiencia;
    private javax.swing.JLabel lbFechaInicioAudiencia1;
    private javax.swing.JLabel lbGuardar;
    private javax.swing.JLabel lbIconoArchivo;
    private javax.swing.JLabel lbIconoGuardar;
    private javax.swing.JLabel lbIconoSubir;
    private javax.swing.JLabel lbIntancia;
    private javax.swing.JLabel lbJuzgado;
    private javax.swing.JLabel lbLinea;
    private javax.swing.JLabel lbNombreApellido;
    private javax.swing.JLabel lbNombreArchivo;
    private javax.swing.JLabel lbNrAudiencia;
    private javax.swing.JLabel lbSentencia;
    private javax.swing.JLabel lbSubirArchivo;
    private javax.swing.JRadioButton rbCulpable;
    private javax.swing.JRadioButton rbEnProceso;
    private javax.swing.JRadioButton rbFinalizado;
    private javax.swing.JRadioButton rbInocente;
    private javax.swing.JRadioButton rbPresuntoCulpable;
    private javax.swing.JTextField txArt;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtIntancia;
    private javax.swing.JTextField txtNombreApellido;
    private javax.swing.JTextField txtNrAudiencia;
    private javax.swing.JTextArea txtSentencia;
    // End of variables declaration//GEN-END:variables
}
