/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.JuzgadoDao;
import Controlador.Utilidades.UtilGesJuz;
import Modelo.Juzgado;
import Vista.Utiles.GestionCeldas;
import Vista.Utiles.GestionEncabezadoTabla;
import Vista.Utiles.ModeloTabla;
import Vista.Utiles.TablaJuzgados.UtilidadesTablaJuzgado;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hp
 */
public class GestionarJuzgados extends javax.swing.JPanel {

    /**
     * Creates new form AgregarJuzgados
     */
    ArrayList<Juzgado> listaJuzgado = new ArrayList<>();
    ModeloTabla modelo;

    private JuzgadoDao jd = new JuzgadoDao();
    private Juzgado jzEditar = new Juzgado();
    private boolean sePuedeEditar;

    public GestionarJuzgados() {
        initComponents();
        listaJuzgado = jd.findJuzgadoEntities(true);
        sePuedeEditar = false;
        construirTabla();
    }

    /**
     * Limpia/Vacia todos los campos
     */
    public void vaciarTxt() {
        txtNombreJuzgado.setText("");
        txtDireccion.setText("");
    }

    /**
     * Construye la tabla segun los datos y titulos
     */
    private void construirTabla() {
        ArrayList<String> titulosList = new ArrayList<>();

        titulosList.add("Nombre");
        titulosList.add("Dirección");
        titulosList.add("Estado");
        titulosList.add(" ");
        titulosList.add(" ");

        //se asignan las columnas al arreglo para enviarse al momento de construir la tabla
        String titulos[] = new String[titulosList.size()];
        for (int i = 0; i < titulos.length; i++) {
            titulos[i] = titulosList.get(i);
        }
        /*obtenemos los datos de la lista y los guardamos en la matriz
		 * que luego se manda a construir la tabla
         */
        Object[][] data = UtilGesJuz.obtenerMatrizDatos(titulosList, listaJuzgado);
        construirTabla(titulos, data);

    }

    /**
     * Construye la tabla segun los datos y botones
     *
     * @param titulos
     * @param data
     */
    private void construirTabla(String[] titulos, Object[][] data) {
        modelo = new ModeloTabla(data, titulos);
        modelo.setRowCount(0);
        modelo = new ModeloTabla(data, titulos);
        //se asigna el modelo a la tabla
        tablaJuzgados.setModel(modelo);

        //se asigna el tipo de dato que tendrón las celdas de cada columna definida respectivamente para validar su personalización;
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.BORRAR).setCellRenderer(new GestionCeldas("icono"));
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.EDITAR).setCellRenderer(new GestionCeldas("icono"));

        //se recorre y asigna el resto de celdas que serian las que almacenen datos de tipo texto
        for (int i = 0; i < titulos.length - 2; i++) {//se resta 2 porque las ultimas 2 columnas se definen arriba
            tablaJuzgados.getColumnModel().getColumn(i).setCellRenderer(new GestionCeldas("texto"));
        }

        tablaJuzgados.getTableHeader().setReorderingAllowed(false);
        tablaJuzgados.setRowHeight(25);//tamano de las celdas
        tablaJuzgados.setGridColor(new java.awt.Color(0, 0, 0));
        //Se define el tamaño de largo para cada columna y su contenido
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.NOMBRE).setPreferredWidth(250);
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.DIRECCION).setPreferredWidth(250);
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.ESTADO).setPreferredWidth(250);
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.BORRAR).setPreferredWidth(35);
        tablaJuzgados.getColumnModel().getColumn(UtilidadesTablaJuzgado.EDITAR).setPreferredWidth(35);

        //personaliza el encabezado
        JTableHeader jtableHeader = tablaJuzgados.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tablaJuzgados.setTableHeader(jtableHeader);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreJuzgado = new javax.swing.JTextField();
        lbNombreJuzgado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JPanel();
        IconoBuscar = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JPanel();
        lbIconoGuardar = new javax.swing.JLabel();
        lbGuardar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJuzgados = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1000, 610));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        LabelTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        LabelTitulo.setText("ADMINISTAR ANTECEDENTES");
        LabelTitulo.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoJuzgados2.png"))); // NOI18N

        txtNombreJuzgado.setBackground(new java.awt.Color(240, 240, 240));
        txtNombreJuzgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreJuzgadoActionPerformed(evt);
            }
        });

        lbNombreJuzgado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNombreJuzgado.setText("Nombre:");
        lbNombreJuzgado.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        botonBuscar.setBackground(new java.awt.Color(18, 44, 82));
        botonBuscar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        IconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoBuscar1.png"))); // NOI18N

        lbBuscar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(204, 206, 223));
        lbBuscar.setText("Buscar");

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(IconoBuscar)
                .addContainerGap())
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoBuscar)
                    .addComponent(lbBuscar))
                .addGap(0, 0, 0))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");

        lbDireccion.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDireccion.setText("Dirección:");
        lbDireccion.setToolTipText("");

        txtDireccion.setBackground(new java.awt.Color(240, 240, 240));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(18, 44, 82));
        botonGuardar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        lbIconoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoGuardar.png"))); // NOI18N

        lbGuardar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbGuardar.setForeground(new java.awt.Color(204, 206, 223));
        lbGuardar.setText("Guardar");

        javax.swing.GroupLayout botonGuardarLayout = new javax.swing.GroupLayout(botonGuardar);
        botonGuardar.setLayout(botonGuardarLayout);
        botonGuardarLayout.setHorizontalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lbIconoGuardar)
                .addContainerGap())
        );
        botonGuardarLayout.setVerticalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconoGuardar)
                    .addComponent(lbGuardar))
                .addGap(0, 0, 0))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablaJuzgados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaJuzgados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJuzgadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaJuzgadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablaJuzgadosMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tablaJuzgados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(LabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDireccion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNombreJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbNombreJuzgado)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreJuzgado)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 810, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreJuzgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreJuzgadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreJuzgadoActionPerformed
    /**
     * Busca la informacion de un Juzgado por el nombre
     *
     * @param evt
     */
    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        if ((txtNombreJuzgado.getText().length() > 0 && txtDireccion.getText().length() > 0) || (txtDireccion.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Solo se puede buscar por el nombre del Juzgado");
        } else if (txtNombreJuzgado.getText().length() > 0) {
            int pos = UtilGesJuz.obtenerJuzgadoContenido(listaJuzgado, txtNombreJuzgado.getText());
            Juzgado aux = listaJuzgado.get(pos);
            jzEditar = jd.find(aux.getIdJuzgado());
            txtNombreJuzgado.setText(jzEditar.getNombre());
            txtDireccion.setText(jzEditar.getDireccionJuzgado());
            sePuedeEditar = true;
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar el campo del Nombre");
        }
    }//GEN-LAST:event_botonBuscarMouseClicked

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed
    /**
     * Permite ingresar un nuevo Juzgado o Editar la infomación de uno
     * dependiendo de lo que se necesite
     *
     * @param evt
     */
    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        if (txtNombreJuzgado.getText().length() > 0 && txtDireccion.getText().length() > 0) {
            boolean esValido = false;
            if (sePuedeEditar) {
                sePuedeEditar = false;
                Juzgado aux = new Juzgado(jzEditar.getIdJuzgado(), txtNombreJuzgado.getText(), txtDireccion.getText(), jzEditar.getEstadoJuzgado());
                if (!UtilGesJuz.datoRepetido(listaJuzgado, aux)) {
                    jd.edit(aux);
                    jzEditar = new Juzgado();
                    if (jd.isSeGuardo()) {
                        JOptionPane.showMessageDialog(null, "Se ha modificado con exito");
                        esValido = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al modificar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este juzgado ya se encuentra registrado");
                }
            } else {
                Juzgado aux = new Juzgado(Long.valueOf(listaJuzgado.size() + 1), txtNombreJuzgado.getText(), txtDireccion.getText(), "Activado");
                if (!UtilGesJuz.datoRepetido(listaJuzgado, aux)) {
                    jd.create(aux);
                    if (jd.isSeGuardo()) {
                        JOptionPane.showMessageDialog(null, "Se ha guardado con exito");
                        esValido = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este juzgado ya se encuentra registrado");
                }
            }
            if (esValido) {
                listaJuzgado = jd.findJuzgadoEntities(true);
                vaciarTxt();
                construirTabla();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los parametros");
        }
    }//GEN-LAST:event_botonGuardarMouseClicked
    /**
     * Permite realizar las acciones de editar y dar de baja seleccionando los
     * determinados iconos de la tabla
     *
     * @param evt
     */
    private void tablaJuzgadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuzgadosMouseClicked
        //capturo fila o columna dependiendo de mi necesidad
        int fila = tablaJuzgados.rowAtPoint(evt.getPoint());
        int columna = tablaJuzgados.columnAtPoint(evt.getPoint());

        /*uso la columna para valiar si corresponde a la columna de perfil garantizando
        * que solo se produzca algo si selecciono una fila de esa columna
         */
        if (columna == UtilidadesTablaJuzgado.BORRAR) {
            Juzgado aux = listaJuzgado.get(fila);
            jd.destroy(aux.getIdJuzgado());
            if (jd.isSeGuardo()) {
                JOptionPane.showMessageDialog(null, "Se ha modificado el estado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el estado correctamente");
            }
        } else if (columna == UtilidadesTablaJuzgado.EDITAR) {//se valida que sea la columna del otro evento
            Juzgado aux = listaJuzgado.get(fila);
            jzEditar = jd.find(aux.getIdJuzgado());
            txtNombreJuzgado.setText(jzEditar.getNombre());
            txtDireccion.setText(jzEditar.getDireccionJuzgado());
            sePuedeEditar = true;
        }
        listaJuzgado = jd.findJuzgadoEntities(true);
        construirTabla();
    }//GEN-LAST:event_tablaJuzgadosMouseClicked

    private void tablaJuzgadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuzgadosMouseEntered

    }//GEN-LAST:event_tablaJuzgadosMouseEntered

    private void tablaJuzgadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuzgadosMouseExited

    }//GEN-LAST:event_tablaJuzgadosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoBuscar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JPanel botonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbGuardar;
    private javax.swing.JLabel lbIconoGuardar;
    private javax.swing.JLabel lbNombreJuzgado;
    private javax.swing.JTable tablaJuzgados;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreJuzgado;
    // End of variables declaration//GEN-END:variables
}
