/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Acces.ControlAcceso;
import Vista.Utiles.ControladorAnimaciones;
import ControlAdminDatos.Utiles.Utiles;
import Controlador.CrearDirectorios;
import Controlador.MantenerCokie;
import Modelo.Persona;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cris2
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    CrearDirectorios create=new CrearDirectorios();
    ControladorAnimaciones animacion = new ControladorAnimaciones();
    AgregarAntecedentes agregarAntecedentes = new AgregarAntecedentes();
    GestionarJuzgados gestionarJuzgados = new GestionarJuzgados();
    AgregarPersonas agregarPersonas = new AgregarPersonas();
    GestionarAntecedentes gestionarAntecedentes = new GestionarAntecedentes();
    GestionarPersonas gestionarPersonas = new GestionarPersonas();
    Cuenta cuenta = new Cuenta();
    Inicio inicio = new Inicio();
    Color InitSesion;
    int heightitem = 200;
    int posicion = 170;
    int indicador;
    Utiles uti = new Utiles();
    ImageIcon img;

    public VistaPrincipal() {
        initComponents();
      
        cortina();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Vista/Iconos/icono.png"));
        setIconImage(iconoPropio);
        //Image iconoEncabezado = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Vista/Iconos/IconoTriangulo1.png"));
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(inicio, 3);
        inicio.setBounds(0, 35, 1000, 625);
        indicador = 1;
        for (int i = 0; i < Menu4.getMouseListeners().length; i++) {
            Menu4.removeMouseListener(Menu4.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu7.getMouseListeners().length; i++) {
            Menu7.removeMouseListener(Menu7.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu10.getMouseListeners().length; i++) {
            Menu10.removeMouseListener(Menu10.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu13.getMouseListeners().length; i++) {
            Menu13.removeMouseListener(Menu13.getMouseListeners()[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        btnMenu = new javax.swing.JLabel();
        panelMenuL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MenuDesplegable1 = new javax.swing.JPanel();
        Menu1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MenuDesplegable2 = new javax.swing.JPanel();
        Menu4 = new javax.swing.JPanel();
        visto1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Menu5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Menu6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        MenuDesplegable3 = new javax.swing.JPanel();
        Menu7 = new javax.swing.JPanel();
        visto2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Menu8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Menu9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        MenuDesplegable4 = new javax.swing.JPanel();
        Menu10 = new javax.swing.JPanel();
        visto3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Menu11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        MenuDesplegable5 = new javax.swing.JPanel();
        Menu13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        visto4 = new javax.swing.JLabel();
        Menu14 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Menu15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        inicioCesion = new javax.swing.JLabel();
        fotop = new rojerusan.RSPanelCircleImage();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Contenedor.setBackground(new java.awt.Color(204, 204, 255));
        Contenedor.setMinimumSize(new java.awt.Dimension(1000, 625));
        Contenedor.setLayout(null);

        btnMenu.setBackground(new java.awt.Color(18, 44, 82));
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-menu-30.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setOpaque(true);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
        });
        Contenedor.add(btnMenu);
        btnMenu.setBounds(230, 35, 40, 30);

        jPanel2.setBackground(new java.awt.Color(18, 44, 82));
        jPanel2.setMinimumSize(new java.awt.Dimension(230, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 700));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(null);

        MenuDesplegable1.setBackground(new java.awt.Color(25, 51, 89));
        MenuDesplegable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuDesplegable1.setPreferredSize(new java.awt.Dimension(210, 50));
        MenuDesplegable1.setLayout(null);

        Menu1.setBackground(new java.awt.Color(18, 44, 82));
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu1MousePressed(evt);
            }
        });
        Menu1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(54, 70, 78));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCasa1.png"))); // NOI18N
        jLabel3.setText("Inicio");
        jLabel3.setIconTextGap(10);
        Menu1.add(jLabel3);
        jLabel3.setBounds(10, 0, 170, 50);

        MenuDesplegable1.add(Menu1);
        Menu1.setBounds(0, 0, 230, 50);

        jPanel2.add(MenuDesplegable1);
        MenuDesplegable1.setBounds(0, 110, 230, 50);

        MenuDesplegable2.setBackground(new java.awt.Color(25, 51, 89));
        MenuDesplegable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuDesplegable2.setPreferredSize(new java.awt.Dimension(210, 50));
        MenuDesplegable2.setLayout(null);

        Menu4.setBackground(new java.awt.Color(18, 44, 82));
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu4MousePressed(evt);
            }
        });
        Menu4.setLayout(null);

        visto1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        visto1.setForeground(new java.awt.Color(255, 255, 255));
        visto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visto1.setText("◄");
        Menu4.add(visto1);
        visto1.setBounds(180, 0, 40, 50);

        jLabel12.setBackground(new java.awt.Color(54, 70, 78));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N
        jLabel12.setText("Antecedentes");
        jLabel12.setIconTextGap(10);
        Menu4.add(jLabel12);
        jLabel12.setBounds(10, 0, 220, 50);

        MenuDesplegable2.add(Menu4);
        Menu4.setBounds(0, 0, 230, 50);

        Menu5.setBackground(new java.awt.Color(18, 44, 82));
        Menu5.setOpaque(false);
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu5MousePressed(evt);
            }
        });
        Menu5.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar");
        Menu5.add(jLabel13);
        jLabel13.setBounds(40, 0, 170, 50);

        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("●");
        Menu5.add(jLabel14);
        jLabel14.setBounds(0, 0, 40, 50);

        MenuDesplegable2.add(Menu5);
        Menu5.setBounds(0, 50, 230, 50);

        Menu6.setBackground(new java.awt.Color(18, 44, 82));
        Menu6.setOpaque(false);
        Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu6MousePressed(evt);
            }
        });
        Menu6.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Gestionar");
        Menu6.add(jLabel15);
        jLabel15.setBounds(40, 0, 170, 50);

        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("●");
        Menu6.add(jLabel16);
        jLabel16.setBounds(0, 0, 40, 50);

        MenuDesplegable2.add(Menu6);
        Menu6.setBounds(0, 100, 230, 50);

        jPanel2.add(MenuDesplegable2);
        MenuDesplegable2.setBounds(0, 170, 230, 50);

        MenuDesplegable3.setBackground(new java.awt.Color(25, 51, 89));
        MenuDesplegable3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuDesplegable3.setPreferredSize(new java.awt.Dimension(210, 50));
        MenuDesplegable3.setLayout(null);

        Menu7.setBackground(new java.awt.Color(18, 44, 82));
        Menu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu7MousePressed(evt);
            }
        });
        Menu7.setLayout(null);

        visto2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        visto2.setForeground(new java.awt.Color(255, 255, 255));
        visto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visto2.setText("◄");
        Menu7.add(visto2);
        visto2.setBounds(180, 0, 40, 50);

        jLabel17.setBackground(new java.awt.Color(54, 70, 78));
        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersonas.png"))); // NOI18N
        jLabel17.setText("Personas");
        jLabel17.setIconTextGap(10);
        Menu7.add(jLabel17);
        jLabel17.setBounds(10, 0, 220, 50);

        MenuDesplegable3.add(Menu7);
        Menu7.setBounds(0, 0, 230, 50);

        Menu8.setBackground(new java.awt.Color(18, 44, 82));
        Menu8.setOpaque(false);
        Menu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu8MousePressed(evt);
            }
        });
        Menu8.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Agregar");
        Menu8.add(jLabel18);
        jLabel18.setBounds(40, 0, 170, 50);

        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("●");
        Menu8.add(jLabel19);
        jLabel19.setBounds(0, 0, 40, 50);

        MenuDesplegable3.add(Menu8);
        Menu8.setBounds(0, 50, 230, 50);

        Menu9.setBackground(new java.awt.Color(18, 44, 82));
        Menu9.setOpaque(false);
        Menu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu9MousePressed(evt);
            }
        });
        Menu9.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Gestionar");
        Menu9.add(jLabel20);
        jLabel20.setBounds(40, 0, 170, 50);

        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("●");
        Menu9.add(jLabel21);
        jLabel21.setBounds(0, 0, 40, 50);

        MenuDesplegable3.add(Menu9);
        Menu9.setBounds(0, 100, 230, 50);

        jPanel2.add(MenuDesplegable3);
        MenuDesplegable3.setBounds(0, 230, 230, 50);

        MenuDesplegable4.setBackground(new java.awt.Color(25, 51, 89));
        MenuDesplegable4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuDesplegable4.setPreferredSize(new java.awt.Dimension(210, 50));
        MenuDesplegable4.setLayout(null);

        Menu10.setBackground(new java.awt.Color(18, 44, 82));
        Menu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu10MousePressed(evt);
            }
        });
        Menu10.setLayout(null);

        visto3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        visto3.setForeground(new java.awt.Color(255, 255, 255));
        visto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visto3.setText("◄");
        Menu10.add(visto3);
        visto3.setBounds(180, 0, 40, 50);

        jLabel22.setBackground(new java.awt.Color(54, 70, 78));
        jLabel22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoJuzgado.png"))); // NOI18N
        jLabel22.setText("Juzgados");
        jLabel22.setIconTextGap(10);
        Menu10.add(jLabel22);
        jLabel22.setBounds(10, 0, 220, 50);

        MenuDesplegable4.add(Menu10);
        Menu10.setBounds(0, 0, 230, 50);

        Menu11.setBackground(new java.awt.Color(18, 44, 82));
        Menu11.setOpaque(false);
        Menu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu11MousePressed(evt);
            }
        });
        Menu11.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Agregar");
        Menu11.add(jLabel23);
        jLabel23.setBounds(40, 0, 170, 50);

        jLabel24.setForeground(new java.awt.Color(255, 153, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("●");
        Menu11.add(jLabel24);
        jLabel24.setBounds(0, 0, 40, 50);

        MenuDesplegable4.add(Menu11);
        Menu11.setBounds(0, 50, 230, 50);

        jPanel2.add(MenuDesplegable4);
        MenuDesplegable4.setBounds(0, 290, 230, 50);

        MenuDesplegable5.setBackground(new java.awt.Color(25, 51, 89));
        MenuDesplegable5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuDesplegable5.setPreferredSize(new java.awt.Dimension(210, 50));
        MenuDesplegable5.setLayout(null);

        Menu13.setBackground(new java.awt.Color(18, 44, 82));
        Menu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu13MousePressed(evt);
            }
        });
        Menu13.setLayout(null);

        jLabel27.setBackground(new java.awt.Color(54, 70, 78));
        jLabel27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoSettings.png"))); // NOI18N
        jLabel27.setText("Setttings");
        jLabel27.setIconTextGap(10);
        Menu13.add(jLabel27);
        jLabel27.setBounds(10, 0, 180, 50);

        visto4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        visto4.setForeground(new java.awt.Color(255, 255, 255));
        visto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visto4.setText("◄");
        Menu13.add(visto4);
        visto4.setBounds(180, 0, 40, 50);

        MenuDesplegable5.add(Menu13);
        Menu13.setBounds(0, 0, 230, 50);

        Menu14.setBackground(new java.awt.Color(18, 44, 82));
        Menu14.setOpaque(false);
        Menu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu14MousePressed(evt);
            }
        });
        Menu14.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Cuenta");
        Menu14.add(jLabel28);
        jLabel28.setBounds(40, 0, 170, 50);

        jLabel29.setForeground(new java.awt.Color(255, 153, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("●");
        Menu14.add(jLabel29);
        jLabel29.setBounds(0, 0, 40, 50);

        MenuDesplegable5.add(Menu14);
        Menu14.setBounds(0, 50, 230, 50);

        Menu15.setBackground(new java.awt.Color(18, 44, 82));
        Menu15.setOpaque(false);
        Menu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu15MousePressed(evt);
            }
        });
        Menu15.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Cerrar cesion");
        Menu15.add(jLabel30);
        jLabel30.setBounds(40, 0, 170, 50);

        jLabel31.setForeground(new java.awt.Color(255, 153, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("●");
        Menu15.add(jLabel31);
        jLabel31.setBounds(0, 0, 40, 50);

        MenuDesplegable5.add(Menu15);
        Menu15.setBounds(0, 100, 230, 50);

        jPanel2.add(MenuDesplegable5);
        MenuDesplegable5.setBounds(0, 350, 230, 50);

        javax.swing.GroupLayout panelMenuLLayout = new javax.swing.GroupLayout(panelMenuL);
        panelMenuL.setLayout(panelMenuLLayout);
        panelMenuLLayout.setHorizontalGroup(
            panelMenuLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLLayout.setVerticalGroup(
            panelMenuLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Contenedor.add(panelMenuL);
        panelMenuL.setBounds(0, 35, 230, 600);

        jButton1.setContentAreaFilled(false);
        Contenedor.add(jButton1);
        jButton1.setBounds(-7, 30, 1010, 610);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioCesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inicioCesion.setForeground(new java.awt.Color(255, 255, 255));
        inicioCesion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inicioCesion.setText("IniciarCesion");
        inicioCesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicioCesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioCesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioCesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inicioCesionMousePressed(evt);
            }
        });
        jPanel3.add(inicioCesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 7, 260, 20));

        fotop.setColorBorde(new java.awt.Color(18, 44, 82));
        fotop.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/UsuarioImg.png"))); // NOI18N

        javax.swing.GroupLayout fotopLayout = new javax.swing.GroupLayout(fotop);
        fotop.setLayout(fotopLayout);
        fotopLayout.setHorizontalGroup(
            fotopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        fotopLayout.setVerticalGroup(
            fotopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(fotop, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, -3, 40, 40));

        jLabel2.setBackground(new java.awt.Color(18, 44, 82));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        Contenedor.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited

    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void Menu15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu15MouseExited
        exited(Menu15, MenuDesplegable5, heightitem, 50);
    }//GEN-LAST:event_Menu15MouseExited

    private void Menu15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu15MouseEntered
        entered(Menu15);
    }//GEN-LAST:event_Menu15MouseEntered

    private void Menu14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu14MouseExited
        exited(Menu14, MenuDesplegable5, heightitem, 50);
    }//GEN-LAST:event_Menu14MouseExited

    private void Menu14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu14MouseEntered
        entered(Menu14);
    }//GEN-LAST:event_Menu14MouseEntered

    private void Menu13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu13MousePressed
        //Desplega un subitems al presionar un item en el menu y controla su comportamiento
        cortina();
        if (MenuDesplegable2.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu4);
        } else if (MenuDesplegable3.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu7);
        } else if (MenuDesplegable4.getSize().height == heightitem - 100) {
            animacion.colorColapse(Menu10);
        } else if (MenuDesplegable1.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu1);
        } else {
            animacion.animacionItems(Menu13, MenuDesplegable5, visto4, heightitem - 50, 50, 2, 0);
        }

    }//GEN-LAST:event_Menu13MousePressed

    private void Menu13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu13MouseExited
        exited(Menu13, MenuDesplegable5, heightitem, 50);
    }//GEN-LAST:event_Menu13MouseExited

    private void Menu13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu13MouseEntered
        entered(Menu13);
    }//GEN-LAST:event_Menu13MouseEntered

    private void Menu11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu11MousePressed
        //Adiciona un JPANEL al contenedor y remueve el que anterior estaba ocupando ese espacio en el contenedor
        cortina();
        Contenedor.remove(inicio);
        Contenedor.remove(agregarAntecedentes);
        Contenedor.remove(cuenta);
        Contenedor.remove(agregarPersonas);
        Contenedor.remove(gestionarAntecedentes);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(gestionarPersonas);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(gestionarJuzgados, 3);
        gestionarJuzgados.setBounds(0, 35, 1000, 625);
        indicador = 6;

    }//GEN-LAST:event_Menu11MousePressed

    private void Menu11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu11MouseExited
        exited(Menu11, MenuDesplegable4, heightitem, 50);// TODO add your handling code here:
    }//GEN-LAST:event_Menu11MouseExited

    private void Menu11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu11MouseEntered
        entered(Menu11);// TODO add your handling code here:
    }//GEN-LAST:event_Menu11MouseEntered

    private void Menu10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu10MousePressed
        //agregar retardo=================
        //Desplega un subitems al presionar un item en el menu y controla su comportamiento
        cortina();
        if (MenuDesplegable2.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu4);
        } else if (MenuDesplegable3.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu7);
        } else if (MenuDesplegable1.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu1);
        } else if (MenuDesplegable5.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu13);
        } else {
            animacion.animacionItems(Menu10, MenuDesplegable4, visto3, heightitem - 100, 50, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable5, posicion + 180, posicion + 230, 2, 0);
        }

    }//GEN-LAST:event_Menu10MousePressed

    private void Menu10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu10MouseExited
        exited(Menu10, MenuDesplegable4, heightitem, 50);
    }//GEN-LAST:event_Menu10MouseExited

    private void Menu10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu10MouseEntered

        entered(Menu10);
    }//GEN-LAST:event_Menu10MouseEntered

    private void Menu9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu9MousePressed
        cortina();
        if (rootPaneCheckingEnabled) {

        }
        gestionarPersonas.actualizar();
        Contenedor.remove(inicio);
        Contenedor.remove(agregarAntecedentes);
        Contenedor.remove(agregarPersonas);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(gestionarAntecedentes);
        Contenedor.remove(cuenta);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(gestionarPersonas, 3);
        gestionarPersonas.setBounds(0, 35, 1000, 625);
        indicador = 6;

    }//GEN-LAST:event_Menu9MousePressed

    private void Menu9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu9MouseExited
        exited(Menu9, MenuDesplegable3, heightitem, 50);
    }//GEN-LAST:event_Menu9MouseExited

    private void Menu9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu9MouseEntered
        entered(Menu9);
    }//GEN-LAST:event_Menu9MouseEntered

    private void Menu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu8MousePressed
        cortina();
        Contenedor.remove(inicio);
        Contenedor.remove(agregarAntecedentes);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(gestionarAntecedentes);
        Contenedor.remove(gestionarPersonas);
        Contenedor.remove(cuenta);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(agregarPersonas, 3);
        agregarPersonas.setBounds(0, 35, 1000, 625);
        indicador = 5;

    }//GEN-LAST:event_Menu8MousePressed

    private void Menu8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu8MouseExited
        exited(Menu8, MenuDesplegable3, heightitem, 50);
    }//GEN-LAST:event_Menu8MouseExited

    private void Menu8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu8MouseEntered
        entered(Menu8);
    }//GEN-LAST:event_Menu8MouseEntered

    private void Menu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu7MousePressed
        //Desplega un subitems al presionar un item en el menu y controla su comportamiento
        cortina();
        if (MenuDesplegable2.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu4);
        } else if (MenuDesplegable1.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu1);
        } else if (MenuDesplegable4.getSize().height == heightitem - 100) {
            animacion.colorColapse(Menu10);
        } else if (MenuDesplegable5.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu13);
        } else {
            animacion.animacionItems(Menu7, MenuDesplegable3, visto2, heightitem - 50, 50, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable4, posicion + 120, posicion + 220, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable5, posicion + 180, posicion + 280, 2, 0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Menu7MousePressed

    private void Menu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu7MouseExited
        exited(Menu7, MenuDesplegable3, heightitem - 50, 50);
    }//GEN-LAST:event_Menu7MouseExited

    private void Menu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu7MouseEntered

        entered(Menu7);
    }//GEN-LAST:event_Menu7MouseEntered

    private void Menu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MousePressed
        cortina();
        Contenedor.remove(inicio);
        Contenedor.remove(agregarAntecedentes);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(gestionarPersonas);
        Contenedor.remove(agregarPersonas);
        Contenedor.remove(cuenta);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(gestionarAntecedentes, 3);
        gestionarAntecedentes.setBounds(0, 35, 1000, 625);
        indicador = 4;

    }//GEN-LAST:event_Menu6MousePressed

    private void Menu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseExited
        exited(Menu6, MenuDesplegable2, heightitem - 50, 50);
    }//GEN-LAST:event_Menu6MouseExited

    private void Menu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseEntered
        entered(Menu6);
    }//GEN-LAST:event_Menu6MouseEntered

    private void Menu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MousePressed
        cortina();
        Contenedor.remove(inicio);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(agregarPersonas);
        Contenedor.remove(gestionarAntecedentes);
        Contenedor.remove(gestionarPersonas);
        Contenedor.remove(cuenta);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(agregarAntecedentes, 3);
        agregarAntecedentes.cargarCombos();
        agregarAntecedentes.setBounds(0, 35, 1000, 625);
        indicador = 3;

    }//GEN-LAST:event_Menu5MousePressed

    private void Menu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseExited
        exited(Menu5, MenuDesplegable2, heightitem - 50, 50);
    }//GEN-LAST:event_Menu5MouseExited

    private void Menu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseEntered
        entered(Menu5);
    }//GEN-LAST:event_Menu5MouseEntered

    private void Menu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MousePressed
        //Desplega un subitems al presionar un item en el menu y controla su comportamiento
        cortina();
        if (MenuDesplegable1.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu1);
        } else if (MenuDesplegable3.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu7);
        } else if (MenuDesplegable4.getSize().height == heightitem - 100) {
            animacion.colorColapse(Menu10);
        } else if (MenuDesplegable5.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu13);
        } else {
            animacion.animacionItems(Menu4, MenuDesplegable2, visto1, heightitem - 50, 50, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable3, posicion + 60, posicion + 160, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable4, posicion + 120, posicion + 220, 2, 0);
            animacion.animacionItemsLocalizacion(MenuDesplegable5, posicion + 180, posicion + 280, 2, 0);
        }

    }//GEN-LAST:event_Menu4MousePressed

    private void Menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseExited
        exited(Menu4, MenuDesplegable2, heightitem - 50, 50);
    }//GEN-LAST:event_Menu4MouseExited

    private void Menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseEntered

        entered(Menu4);
    }//GEN-LAST:event_Menu4MouseEntered

    private void Menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MousePressed
        //Desplega un subitems al presionar un item en el menu y controla su comportamiento
        cortina();
        if (MenuDesplegable2.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu4);
        } else if (MenuDesplegable3.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu7);
        } else if (MenuDesplegable4.getSize().height == heightitem - 100) {
            animacion.colorColapse(Menu10);
        } else if (MenuDesplegable5.getSize().height == heightitem - 50) {
            animacion.colorColapse(Menu13);
        } else {
            Contenedor.remove(agregarAntecedentes);
            Contenedor.remove(gestionarAntecedentes);
            Contenedor.remove(gestionarJuzgados);
            Contenedor.remove(agregarPersonas);
            Contenedor.remove(gestionarPersonas);
            Contenedor.remove(cuenta);
            repaint();
            animacion.animacionPanelMenu(panelMenuL, btnMenu);
            Contenedor.add(inicio, 3);
            inicio.setBounds(0, 35, 1000, 625);
            indicador = 2;

        }
    }//GEN-LAST:event_Menu1MousePressed

    private void Menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseExited
        exited(Menu1, MenuDesplegable1, heightitem, 50);
    }//GEN-LAST:event_Menu1MouseExited

    private void Menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseEntered

        entered(Menu1);
    }//GEN-LAST:event_Menu1MouseEntered

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        System.out.println("dimension definitiva> " + panelMenuL.getSize().width);
        cortina();
    }//GEN-LAST:event_btnMenuMousePressed

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        resetlabelcolor(btnMenu);
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        labelcolor(btnMenu);
    }//GEN-LAST:event_btnMenuMouseEntered

    private void Menu14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu14MousePressed
        //posibles ideas
        cortina();

        Contenedor.remove(inicio);
        Contenedor.remove(agregarPersonas);
        Contenedor.remove(gestionarAntecedentes);
        Contenedor.remove(gestionarJuzgados);
        Contenedor.remove(gestionarPersonas);
        Contenedor.remove(agregarAntecedentes);
        Contenedor.remove(cuenta);
        repaint();
        animacion.animacionPanelMenu(panelMenuL, btnMenu);
        Contenedor.add(cuenta, 3);
        cuenta.setBounds(0, 35, 1000, 625);
        indicador = 3;


    }//GEN-LAST:event_Menu14MousePressed
    private void inicioCesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioCesionMouseEntered
        InitSesion = inicioCesion.getForeground();
        inicioCesion.setForeground(Color.GREEN);
    }//GEN-LAST:event_inicioCesionMouseEntered

    private void inicioCesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioCesionMouseExited
        inicioCesion.setForeground(InitSesion);
    }//GEN-LAST:event_inicioCesionMouseExited
    ControlAcceso acces = new ControlAcceso();


    private void inicioCesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioCesionMousePressed
        acces.setVisible(true);
        acces.setLocationRelativeTo(this);
    }//GEN-LAST:event_inicioCesionMousePressed

    private void Menu15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu15MousePressed

        int accion = JOptionPane.showConfirmDialog(null, "Cerrar Cesión");
        MantenerCokie<Persona> cok = new MantenerCokie<>();
        
        if (accion == 0) {
            boolean estado = false;
            while (estado == false) {
                estado=cok.RemoveCokie("Cesion");
            }
            inicioCesion.setText("IniciarCesion");
            cuenta.BorrarPantalla();
            Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Acces/Imagenes/UsuarioImg.png"));
            fotop.setImagen(new ImageIcon(uti.img(img, fotop.getSize())));
            eventosCerrarCesion();
            AnimacionesCerrarCesion();
            System.out.println("Cerrar cesion");

        } else {

            System.out.println("No hace nada");
        }
    }//GEN-LAST:event_Menu15MousePressed
   public void AnimacionesCerrarCesion(){
       //Desplega un subitems al presionar un item en el menu y controla su comportamiento
            if (MenuDesplegable2.getSize().height == heightitem - 50) {
                animacion.colorColapse(Menu4);
            } else if (MenuDesplegable3.getSize().height == heightitem - 50) {
                animacion.colorColapse(Menu7);
            } else if (MenuDesplegable4.getSize().height == heightitem - 100) {
                animacion.colorColapse(Menu10);
            } else if (MenuDesplegable1.getSize().height == heightitem - 50) {
                animacion.colorColapse(Menu1);
            } else {
                animacion.animacionItems(Menu13, MenuDesplegable5, visto4, heightitem - 50, 50, 2, 0);
            }
            Contenedor.remove(cuenta);
            Contenedor.remove(agregarAntecedentes);
            Contenedor.remove(gestionarJuzgados);
            Contenedor.remove(agregarPersonas);
            Contenedor.remove(gestionarPersonas);
            repaint();
            animacion.animacionPanelMenu(panelMenuL, btnMenu);
            Contenedor.add(inicio, 3);
            inicio.setBounds(0, 35, 1000, 625);
            indicador = 2;
   }
    public void eventosCerrarCesion() {
        inicioCesion.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioCesionMouseEntered(evt);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioCesionMouseExited(evt);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inicioCesionMousePressed(evt);
            }
        });
        for (int i = 0; i < Menu4.getMouseListeners().length; i++) {
            Menu4.removeMouseListener(Menu4.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu7.getMouseListeners().length; i++) {
            Menu7.removeMouseListener(Menu7.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu10.getMouseListeners().length; i++) {
            Menu10.removeMouseListener(Menu10.getMouseListeners()[i]);
        }
        for (int i = 0; i < Menu13.getMouseListeners().length; i++) {
            Menu13.removeMouseListener(Menu13.getMouseListeners()[i]);
        }
    }
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        MantenerCokie<Persona> cok = new MantenerCokie<>();

        File file = new File("Cesion" + File.separatorChar + "Cesion.json");
        if (file.exists()) {
            Persona persona = cok.getCokieValue("Cesion");
            inicioCesion.setText(persona.getNombre() + " " + persona.getApellido());
            fotop.setImagen(new ImageIcon("Perfiles/"+persona.getFile().getPath()));

            for (int i = 0; i < inicioCesion.getMouseListeners().length; i++) {
                inicioCesion.removeMouseListener(inicioCesion.getMouseListeners()[i]);

            }
            Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    Menu4MouseEntered(evt);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    Menu4MouseExited(evt);
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    Menu4MousePressed(evt);
                }
            });
            Menu7.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    Menu7MouseEntered(evt);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    Menu7MouseExited(evt);
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    Menu7MousePressed(evt);
                }
            });
            Menu10.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    Menu10MouseEntered(evt);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    Menu10MouseExited(evt);
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    Menu10MousePressed(evt);
                }
            });
            Menu13.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    Menu13MouseEntered(evt);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    Menu13MouseExited(evt);
                }

                public void mousePressed(java.awt.event.MouseEvent evt) {
                    Menu13MousePressed(evt);
                }
            });
            cuenta.actualizarPantalla();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed

    }//GEN-LAST:event_jLabel2MousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    public void cortina() {
        //metodo que agrega una especie de cortina que bloque cualquier accion del
        //usuario sobre el lienso del contenedor cuando el menu esta desplegado evitando problemas
        if (panelMenuL.getSize().width == 0) {
            jButton1.setVisible(true);

        } else {
            jButton1.setVisible(false);

            System.out.println("false");
        }
    }

    private void entered(JPanel item) {
        //metodo que controla lo que sucede cuado el mause es colocado sobre un item o subitem del menu
        item.setOpaque(true);
        item.setBackground(new Color(18, 77, 123));
    }

    private void exited(JPanel item, JPanel menu, int max, int min) {
        //metodo que controla lo que sucede cuado el mause es retirado de sobre un item o subitem del menu
        if (menu.getSize().height == min) {
            item.setOpaque(true);
        } else if (menu.getSize().height == max) {
            item.setOpaque(false);
        }
        item.setBackground(new Color(18, 44, 82));
    }

    private void labelcolor(JLabel label) {
        //cambia de color a un JLabel
        label.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void resetlabelcolor(JLabel label) {
        //restablece de color a un JLabel
        label.setBackground(new java.awt.Color(18, 44, 82));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//           
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu10;
    private javax.swing.JPanel Menu11;
    private javax.swing.JPanel Menu13;
    private javax.swing.JPanel Menu14;
    private javax.swing.JPanel Menu15;
    private javax.swing.JPanel Menu4;
    private javax.swing.JPanel Menu5;
    private javax.swing.JPanel Menu6;
    private javax.swing.JPanel Menu7;
    private javax.swing.JPanel Menu8;
    private javax.swing.JPanel Menu9;
    private javax.swing.JPanel MenuDesplegable1;
    private javax.swing.JPanel MenuDesplegable2;
    private javax.swing.JPanel MenuDesplegable3;
    private javax.swing.JPanel MenuDesplegable4;
    private javax.swing.JPanel MenuDesplegable5;
    private javax.swing.JLabel btnMenu;
    private rojerusan.RSPanelCircleImage fotop;
    private javax.swing.JLabel inicioCesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelMenuL;
    private javax.swing.JLabel visto1;
    private javax.swing.JLabel visto2;
    private javax.swing.JLabel visto3;
    private javax.swing.JLabel visto4;
    // End of variables declaration//GEN-END:variables
}
