/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Acces;

import ControlAdminDatos.Utiles.Utiles;
import Controlador.ControladorCuenta;
import Controlador.ControladorPersona;
import Vista.Utiles.TablaPersonas.ConvertirEnums;
import Vista.Utiles.TablaPersonas.Sexo;
import Vista.Utiles.UtilesFecha;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro1
     */
    UtilesFecha fech = new UtilesFecha();
    /**
     * Constructor de la clase Registro
     * @param aL Evento pasado por parametro
     */
    public Registro(MouseListener aL) {
        ConvertirEnums enums = new ConvertirEnums();
        initComponents();
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(enums.convertSexo(Sexo.values())));
        btnRegresar.addMouseListener(aL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedulaValida = new javax.swing.JLabel();
        lblEmailValid = new javax.swing.JLabel();
        lblClaveValid = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaNa = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnOk = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        lblUsuarioValido = new javax.swing.JLabel();
        lblNombreValido = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        foto = new rojerusan.RSPanelCircleImage();
        botonluna = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(609, 400));
        setMinimumSize(new java.awt.Dimension(609, 400));
        setLayout(null);

        lblCedulaValida.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblCedulaValida);
        lblCedulaValida.setBounds(310, 160, 150, 14);

        lblEmailValid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblEmailValid);
        lblEmailValid.setBounds(310, 340, 150, 14);

        lblClaveValid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblClaveValid);
        lblClaveValid.setBounds(10, 180, 150, 14);

        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        add(txtUsuario);
        txtUsuario.setBounds(10, 90, 280, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Usuario");
        add(jLabel5);
        jLabel5.setBounds(10, 70, 170, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contraseña");
        add(jLabel6);
        jLabel6.setBounds(10, 130, 170, 15);

        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre);
        txtNombre.setBounds(10, 210, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nombres");
        add(jLabel7);
        jLabel7.setBounds(10, 190, 170, 15);

        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        add(txtApellido);
        txtApellido.setBounds(10, 270, 280, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Sexo");
        add(jLabel8);
        jLabel8.setBounds(10, 310, 100, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Registro");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 170, 30);

        fechaNa.setDateFormatString("dd/MM/yyyy");
        fechaNa.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));
        add(fechaNa);
        fechaNa.setBounds(120, 330, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Apellidos");
        add(jLabel9);
        jLabel9.setBounds(10, 250, 170, 15);

        cbSexo.setBackground(new java.awt.Color(240, 240, 240));
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbSexo);
        cbSexo.setBounds(10, 330, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Fecha de nacimiento");
        add(jLabel10);
        jLabel10.setBounds(120, 310, 170, 15);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn.png"))); // NOI18N
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
        });
        btnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnOkKeyReleased(evt);
            }
        });
        add(btnOk);
        btnOk.setBounds(480, 340, 110, 40);

        btnRegresar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 204, 102));
        btnRegresar.setText("<");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        add(btnRegresar);
        btnRegresar.setBounds(560, 10, 21, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Cedula");
        add(jLabel12);
        jLabel12.setBounds(310, 110, 170, 15);

        txtCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        add(txtCedula);
        txtCedula.setBounds(310, 130, 280, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Direccion");
        add(jLabel13);
        jLabel13.setBounds(310, 170, 170, 15);

        txtDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });
        add(txtDireccion);
        txtDireccion.setBounds(310, 190, 280, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Telefono");
        add(jLabel14);
        jLabel14.setBounds(310, 230, 170, 15);

        txtTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        add(txtTelefono);
        txtTelefono.setBounds(310, 250, 280, 30);

        txtMail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMailKeyReleased(evt);
            }
        });
        add(txtMail);
        txtMail.setBounds(310, 310, 280, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("E-Mail");
        add(jLabel15);
        jLabel15.setBounds(310, 290, 170, 15);

        txtClave.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClaveKeyReleased(evt);
            }
        });
        add(txtClave);
        txtClave.setBounds(10, 150, 280, 30);

        lblUsuarioValido.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblUsuarioValido);
        lblUsuarioValido.setBounds(10, 120, 150, 14);

        lblNombreValido.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblNombreValido);
        lblNombreValido.setBounds(10, 240, 150, 14);

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblApellido);
        lblApellido.setBounds(10, 300, 150, 14);

        lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblDireccion);
        lblDireccion.setBounds(310, 220, 150, 14);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        add(lblTelefono);
        lblTelefono.setBounds(310, 280, 150, 14);

        foto.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/UsuarioImg.png"))); // NOI18N
        foto.setLayout(null);

        botonluna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btonlunapequeño.png"))); // NOI18N
        botonluna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonluna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonlunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonlunaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonlunaMousePressed(evt);
            }
        });
        foto.add(botonluna);
        botonluna.setBounds(-10, 40, 100, 60);

        add(foto);
        foto.setBounds(430, 20, 80, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseEntered
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn1.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btnOkMouseEntered

    private void btnOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseExited
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btnOkMouseExited
    Boolean validaCampoContraseña;
    Boolean validaCampoCedula;
    Boolean validaCampoEmail;
    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        registrar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkMousePressed
    /**
     * Contiene todas las acciones que se ejecutaran al hacer click o enter sobre el boton Ok
     */
    public void registrar() {
        if (validaCampoCedula && validaCampoContraseña && validaCampoEmail && telefonoValido && validaNombre && validaApellido && validaUsuario && validaDireccion && fechaNa.getDate() != null && cbSexo.getSelectedItem() != null) {

            try {
                ControladorPersona ctr = new ControladorPersona();
                ControladorCuenta ctrc = new ControladorCuenta();
                ctr.newPersona();
                SecureRandom sc = new SecureRandom();
                Integer secure = sc.nextInt(1000000);
                Long generator = secure.longValue();
                ctr.agregarPersona().setIdPersona(generator);
                ctr.agregarPersona().setCedula(txtCedula.getText());
                ctr.agregarPersona().setNombre(txtNombre.getText());
                ctr.agregarPersona().setApellido(txtApellido.getText());
                ctr.agregarPersona().setFechaNacimiento(fech.getFecha(fechaNa));
                ctr.agregarPersona().setDireccion(txtDireccion.getText());
                ctr.agregarPersona().setSexo(cbSexo.getSelectedItem().toString());
                ctr.agregarPersona().setTelefono(txtTelefono.getText());
                ctr.agregarPersona().setMail(txtMail.getText());
                ctr.agregarPersona().setFile(file);
                ctr.agregarPersona().setEstado(Boolean.TRUE);
                ctr.agregarPersona().setIdRol(1L);
                ctr.guardarPersona();
                ctrc.newCuenta();
                ctrc.agregarCuenta().setIdCuenta(0L);
                ctrc.agregarCuenta().setClave(ctrc.encriptar(txtClave.getPassword()));
                ctrc.agregarCuenta().setUsuario(txtUsuario.getText());
                ctrc.agregarCuenta().setIdPersona(generator);
                ctrc.guardarCuenta();
                if (ctr.isCorrect()) {
                    txtApellido.setText("");
                    txtCedula.setText("");
                    txtClave.setText("");
                    txtDireccion.setText("");
                    txtMail.setText("");
                    txtNombre.setText("");
                    txtTelefono.setText("");
                    txtUsuario.setText("");
                    lblApellido.setText("");
                    lblCedulaValida.setText("");
                    lblDireccion.setText("");
                    lblEmailValid.setText("");
                    lblNombreValido.setText("");
                    lblTelefono.setText("");
                    lblClaveValid.setText("");
                    lblUsuarioValido.setText("");
                    Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Acces/Imagenes/UsuarioImg.png"));
                    foto.setImagen(new ImageIcon(uti.img(img, foto.getSize())));
                    JOptionPane.showMessageDialog(null, "Registro exitoso");
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el registro");
                }

                // TODO add your handling code here:
            } catch (GeneralSecurityException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Datos faltantes o erroneos");
        }
    }
    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(new Color(102, 196, 67));// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(102, 204, 102));// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseExited

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracteres invalidos solo puede ingresar numeros");
            // ignorar el evento de teclado
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito

        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracteres invalidos solo puede ingresar numeros");
            // ignorar el evento de teclado
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracteres invalidos no se permiten numeros en el Nombre");
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracteres invalidos no se permiten numeros en el Apellido");
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyTyped
    Utiles uti = new Utiles();
    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased

        validaCampoCedula = uti.isEcuadorianDocumentValid(txtCedula.getText());

        if (validaCampoCedula) {
            lblCedulaValida.setText("CI. Valido");
            lblCedulaValida.setForeground(Color.green);
        } else {
            lblCedulaValida.setText("CI. Invalido");
            lblCedulaValida.setForeground(Color.red);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailKeyReleased
        validaCampoEmail = uti.validarDireccionCorreoElectronico(txtMail.getText());
        if (validaCampoEmail) {
            lblEmailValid.setText("Correo. Valido");
            lblEmailValid.setForeground(Color.green);
        } else {
            lblEmailValid.setText("Correo. Invalido");
            lblEmailValid.setForeground(Color.red);
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtMailKeyReleased

    private void txtClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyReleased
        if (txtClave.getPassword().length >= 8) {
            validaCampoContraseña = true;
            lblClaveValid.setText("Contraseña. Valida");
            lblClaveValid.setForeground(Color.green);
        } else {
            validaCampoContraseña = false;
            lblClaveValid.setText("Contraseña. Invalida");
            lblClaveValid.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveKeyReleased
    boolean telefonoValido;
    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        if (txtTelefono.getText().length() == 10) {
            telefonoValido = true;
            lblTelefono.setText("Telefono. Valido");
            lblTelefono.setForeground(Color.green);

        } else {
            telefonoValido = false;
            lblTelefono.setText("Telefono. Invalido");
            lblTelefono.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased
    boolean validaUsuario;
    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        if (txtUsuario.getText().length() > 4) {
            validaUsuario = true;
            lblUsuarioValido.setText("Usuario. Valido");
            lblUsuarioValido.setForeground(Color.green);
        } else {
            validaUsuario = false;
            lblUsuarioValido.setText("Usuario. Invalido");
            lblUsuarioValido.setForeground(Color.red);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyReleased
    boolean validaNombre;
    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if (txtNombre.getText().length() > 7 && txtNombre.getText().contains(" ")) {
            validaNombre = true;
            lblNombreValido.setText("Nombre. Valido");
            lblNombreValido.setForeground(Color.green);
        } else {
            validaNombre = false;
            lblNombreValido.setText("Nombre. Invalido");
            lblNombreValido.setForeground(Color.red);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyReleased
    boolean validaApellido;
    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        if (txtApellido.getText().length() > 7 && txtApellido.getText().contains(" ")) {
            validaApellido = true;
            lblApellido.setText("Apellido. Valido");
            lblApellido.setForeground(Color.green);
        } else {
            validaApellido = false;
            lblApellido.setText("Apellido. Invalido");
            lblApellido.setForeground(Color.red);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyReleased
    boolean validaDireccion;
    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        if (txtDireccion.getText().length() > 8) {
            validaDireccion = true;
            lblDireccion.setText("Dirección. Valida");
            lblDireccion.setForeground(Color.green);
        } else {
            validaDireccion = false;
            lblDireccion.setText("Dirección. Invalida");
            lblDireccion.setForeground(Color.red);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void botonlunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlunaMouseEntered
        botonluna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/botonlunapequeño2.png")));// TODO add your handling code here:
    }//GEN-LAST:event_botonlunaMouseEntered

    private void botonlunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlunaMouseExited
        botonluna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btonlunapequeño.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_botonlunaMouseExited
    File file = null;
    private void botonlunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlunaMousePressed
        file = uti.BuscarImagen();
        if (file != null) {
            ImageIcon ico = new ImageIcon(file.getAbsolutePath());
            foto.setImagen(ico);
        }// TODO add your handling code here:
    }//GEN-LAST:event_botonlunaMousePressed

    private void btnOkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkKeyReleased
        registrar();// TODO add your handling code here:
    }//GEN-LAST:event_btnOkKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonluna;
    private javax.swing.JLabel btnOk;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JComboBox<String> cbSexo;
    private com.toedter.calendar.JDateChooser fechaNa;
    private rojerusan.RSPanelCircleImage foto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedulaValida;
    private javax.swing.JLabel lblClaveValid;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmailValid;
    private javax.swing.JLabel lblNombreValido;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUsuarioValido;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
